### ISSUE TITLE
RF images

### ISSUE THREAD

**Issue by balboajeff** [craftninja/space61#1]
<img width="576" alt="TX_Pic_SpaceCamp" src="https://user-images.githubusercontent.com/3208750/59641482-f4959180-911e-11e9-9967-51e50996629d.png">

**Comment by balboajeff** [comment]
<img width="576" alt="RX_Pic_SpaceCamp" src="https://user-images.githubusercontent.com/3208750/59706312-6f14ee80-91bd-11e9-89e5-27215ed18129.png">

**Comment by craftninja** [comment]
Thanks for these! I'll put them in the presentation. ✨

**Comment by balboajeff** [comment]
![openLog spacecamp](https://user-images.githubusercontent.com/3208750/59723539-34727c80-91e4-11e9-9c27-d1d809c50ddb.jpg)

**Comment by balboajeff** [comment]
![SpaceCamp1](https://user-images.githubusercontent.com/3208750/59724161-24f43300-91e6-11e9-9274-51552f0a83f2.jpg)

**Comment by balboajeff** [comment]
![spacecamp_0](https://user-images.githubusercontent.com/3208750/59724343-b5cb0e80-91e6-11e9-81ee-47971c93f325.jpg)

**Comment by balboajeff** [comment]
![SpaceCamp2](https://user-images.githubusercontent.com/3208750/59724980-1f4c1c80-91e9-11e9-90f5-6566fb30ed8b.jpg)

**Comment by balboajeff** [comment]
![SpaceCamp3](https://user-images.githubusercontent.com/3208750/59725932-dbf3ad00-91ec-11e9-9864-044631d890f8.jpg)

**Comment by balboajeff** [comment]
![SpaceCamp4](https://user-images.githubusercontent.com/3208750/59727879-db5f1480-91f4-11e9-9d1c-95d3387c3fc8.jpg)

**Comment by balboajeff** [comment]
![SpaceCamp5 jpg_bb](https://user-images.githubusercontent.com/3208750/59731481-8c6cab80-9203-11e9-8c40-e3ad5568b586.jpg)

**Comment by craftninja** [comment]
YAS +++
